//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DefaultMISACode {
            get {
                return ResourceManager.GetString("DefaultMISACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch an exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không được để trống.
        /// </summary>
        public static string Error_InvalidData {
            get {
                return ResourceManager.GetString("Error_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string Excel_Table_Name {
            get {
                return ResourceManager.GetString("Excel_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn.
        /// </summary>
        public static string Overtime_ApplyDate {
            get {
                return ResourceManager.GetString("Overtime_ApplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt.
        /// </summary>
        public static string Overtime_ApprovalName {
            get {
                return ResourceManager.GetString("Overtime_ApprovalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca từ.
        /// </summary>
        public static string Overtime_BreakTimeFrom {
            get {
                return ResourceManager.GetString("Overtime_BreakTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca đến.
        /// </summary>
        public static string Overtime_BreakTimeTo {
            get {
                return ResourceManager.GetString("Overtime_BreakTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị công tác.
        /// </summary>
        public static string Overtime_DepartmentName {
            get {
                return ResourceManager.GetString("Overtime_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Overtime_Description {
            get {
                return ResourceManager.GetString("Overtime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký làm thêm đã tồn tại. Vui lòng kiểm tra lại..
        /// </summary>
        public static string OverTime_Duplicate {
            get {
                return ResourceManager.GetString("OverTime_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Overtime_EmployeeCode {
            get {
                return ResourceManager.GetString("Overtime_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nộp đơn.
        /// </summary>
        public static string Overtime_FullName {
            get {
                return ResourceManager.GetString("Overtime_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm làm thêm.
        /// </summary>
        public static string Overtime_OverTimeInWorkingShiftName {
            get {
                return ResourceManager.GetString("Overtime_OverTimeInWorkingShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí công việc.
        /// </summary>
        public static string Overtime_PositionName {
            get {
                return ResourceManager.GetString("Overtime_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do làm thêm.
        /// </summary>
        public static string Overtime_Reason {
            get {
                return ResourceManager.GetString("Overtime_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên quan.
        /// </summary>
        public static string Overtime_RelationShipNames {
            get {
                return ResourceManager.GetString("Overtime_RelationShipNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Overtime_Status {
            get {
                return ResourceManager.GetString("Overtime_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm đến.
        /// </summary>
        public static string Overtime_ToDate {
            get {
                return ResourceManager.GetString("Overtime_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca áp dụng.
        /// </summary>
        public static string Overtime_WorkingShiftName {
            get {
                return ResourceManager.GetString("Overtime_WorkingShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau ca.
        /// </summary>
        public static string OverTimeInWorkingShift_AfterShift {
            get {
                return ResourceManager.GetString("OverTimeInWorkingShift_AfterShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước ca.
        /// </summary>
        public static string OverTimeInWorkingShift_BeforeShift {
            get {
                return ResourceManager.GetString("OverTimeInWorkingShift_BeforeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ.
        /// </summary>
        public static string OverTimeInWorkingShift_DayOff {
            get {
                return ResourceManager.GetString("OverTimeInWorkingShift_DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ giữa ca.
        /// </summary>
        public static string OverTimeInWorkingShift_MiddleShift {
            get {
                return ResourceManager.GetString("OverTimeInWorkingShift_MiddleShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm thêm từ.
        /// </summary>
        public static string Ovettime_FromDate {
            get {
                return ResourceManager.GetString("Ovettime_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SQL Command catch Exception.
        /// </summary>
        public static string ServiceResult_Exception {
            get {
                return ResourceManager.GetString("ServiceResult_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SQL Command return null.
        /// </summary>
        public static string ServiceResult_Fail {
            get {
                return ResourceManager.GetString("ServiceResult_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SQL Command Success.
        /// </summary>
        public static string ServiceResult_Success {
            get {
                return ResourceManager.GetString("ServiceResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        public static string Status_Approved {
            get {
                return ResourceManager.GetString("Status_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Status_Denied {
            get {
                return ResourceManager.GetString("Status_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string Status_Wait {
            get {
                return ResourceManager.GetString("Status_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh TK ngân hàng.
        /// </summary>
        public static string Title_BankBranch {
            get {
                return ResourceManager.GetString("Title_BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string Title_BankName {
            get {
                return ResourceManager.GetString("Title_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string Title_BankNumber {
            get {
                return ResourceManager.GetString("Title_BankNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Title_DateOfBirth {
            get {
                return ResourceManager.GetString("Title_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string Title_Department {
            get {
                return ResourceManager.GetString("Title_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Title_EmployeeCode {
            get {
                return ResourceManager.GetString("Title_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string Title_FullName {
            get {
                return ResourceManager.GetString("Title_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        public static string Title_IdentityNumber {
            get {
                return ResourceManager.GetString("Title_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Title_Index {
            get {
                return ResourceManager.GetString("Title_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string Title_Position {
            get {
                return ResourceManager.GetString("Title_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ trung tâm tư vấn!.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca 1.
        /// </summary>
        public static string WorkingShift_FirstCase {
            get {
                return ResourceManager.GetString("WorkingShift_FirstCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca hành chính.
        /// </summary>
        public static string WorkingShift_InWork {
            get {
                return ResourceManager.GetString("WorkingShift_InWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca đêm.
        /// </summary>
        public static string WorkingShift_NightCase {
            get {
                return ResourceManager.GetString("WorkingShift_NightCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca 2.
        /// </summary>
        public static string WorkingShift_SecondCase {
            get {
                return ResourceManager.GetString("WorkingShift_SecondCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không đúng định dạng (NV-x) với x là số thứ tự nhân viên.
        /// </summary>
        public static string WrongCodeFormat {
            get {
                return ResourceManager.GetString("WrongCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường chỉ được phép chứa số.
        /// </summary>
        public static string WrongOnlyNumberFormat {
            get {
                return ResourceManager.GetString("WrongOnlyNumberFormat", resourceCulture);
            }
        }
    }
}
